/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	attr,
	claim_element,
	detach,
	element,
	init,
	insert,
	listen,
	noop,
	safe_not_equal,
	set_input_value,
	to_number
} from '../../../web_modules/svelte/internal/index.mjs';

function create_fragment(ctx) {
	let input;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			this.h();
		},
		l(nodes) {
			input = claim_element(nodes, "INPUT", { id: true, type: true });
			this.h();
		},
		h() {
			attr(input, "id", /*label*/ ctx[1]);
			attr(input, "type", "number");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*field*/ ctx[0]);

			if (!mounted) {
				dispose = listen(input, "input", /*input_input_handler*/ ctx[2]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*label*/ 2) {
				attr(input, "id", /*label*/ ctx[1]);
			}

			if (dirty & /*field*/ 1 && to_number(input.value) !== /*field*/ ctx[0]) {
				set_input_value(input, /*field*/ ctx[0]);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { field } = $$props, { label } = $$props;

	function input_input_handler() {
		field = to_number(this.value);
		$$invalidate(0, field);
	}

	$$self.$$set = $$props => {
		if ("field" in $$props) $$invalidate(0, field = $$props.field);
		if ("label" in $$props) $$invalidate(1, label = $$props.label);
	};

	return [field, label, input_input_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { field: 0, label: 1 });
	}
}

export default Component;