/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	attr,
	claim_element,
	detach,
	element,
	init,
	insert,
	listen,
	noop,
	safe_not_equal
} from '../../../web_modules/svelte/internal/index.mjs';

import { isTime, inputFormatTime, displayFormatTime } from '../date_checker.js';

function create_fragment(ctx) {
	let input;
	let input_value_value;
	let input_step_value;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			this.h();
		},
		l(nodes) {
			input = claim_element(nodes, "INPUT", { type: true, step: true });
			this.h();
		},
		h() {
			attr(input, "type", "time");

			input.value = input_value_value = isTime(/*field*/ ctx[0])
			? inputFormatTime(/*field*/ ctx[0])
			: null;

			attr(input, "step", input_step_value = /*field*/ ctx[0].split(":").length > 2 ? 1 : 60);
			input.required = true;
		},
		m(target, anchor) {
			insert(target, input, anchor);

			if (!mounted) {
				dispose = listen(input, "input", /*input_handler*/ ctx[2]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*field*/ 1 && input_value_value !== (input_value_value = isTime(/*field*/ ctx[0])
			? inputFormatTime(/*field*/ ctx[0])
			: null)) {
				input.value = input_value_value;
			}

			if (dirty & /*field*/ 1 && input_step_value !== (input_step_value = /*field*/ ctx[0].split(":").length > 2 ? 1 : 60)) {
				attr(input, "step", input_step_value);
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { field } = $$props;
	const bindTime = time => $$invalidate(0, field = displayFormatTime(time, field));
	const input_handler = time => bindTime(time.target.value);

	$$self.$$set = $$props => {
		if ("field" in $$props) $$invalidate(0, field = $$props.field);
	};

	return [field, bindTime, input_handler];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { field: 0 });
	}
}

export default Component;